const {REACT_APP_NETWORK, REACT_APP_MAINNET_URL, REACT_APP_TESTNET_URL, REACT_APP_MAINNET_CHAIN_ID, REACT_APP_TESTNET_CHAIN_ID} = process.env

export const chainId = parseInt(REACT_APP_NETWORK === "MAINNET" ? REACT_APP_MAINNET_CHAIN_ID : (REACT_APP_NETWORK === "TESTNET" ? REACT_APP_TESTNET_CHAIN_ID : REACT_APP_MAINNET_CHAIN_ID));

export const networkUrl = REACT_APP_NETWORK === "MAINNET" ? REACT_APP_MAINNET_URL : (REACT_APP_NETWORK === "TESTNET" ? REACT_APP_TESTNET_URL : REACT_APP_MAINNET_URL);